---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/MediaMath/govent
    steps:
      - checkout
      - run: go get ./...
      - run: make test
